### ISSUE TITLE
Unexpected value 'ImageUploadModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by paruvellyvishwanath** [AndyMeps/ng2-image-upload#1]
i am using angula 2 rc.

when i run npm run buid.it's work fine. probleam is when i run npm run build:prod i am getting below error
 
Unexpected value 'ImageUploadModule' imported by the module 'AppModule'
    at E:\Vishwanath\vasthu_Projet\Vasthu_1\node_modules\@angular\compiler\bundles\compiler.umd.js:14109:37

**my webpack version:** 

  "webpack": "2.1.0-beta.21",
    "webpack-merge": "^0.14.1"

**Comment by AndyMeps** [comment]
Hi paruvellyvishwanath,

Are you still experiencing this issue? If so please can you provide some more detail? Including the version of ng2-image-upload you are using and reproduction steps / example code that doesn't work.

Regards,

Andy

**Comment by paruvellyvishwanath** [comment]
no.i am not getting any issue
